In [ ]:
from google.colab import drive
drive.mount('/content/drive')
!ls /content/drive/MyDrive/5features.mat

In [1]:
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score
import scipy.io as sio
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold
from sklearn.metrics import classification_report
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import GridSearchCV, cross_val_score, KFold
from sklearn.metrics import classification_report, accuracy_score, make_scorer
from sklearn.model_selection import cross_validate
from sklearn.model_selection import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
print('Importing Complete')

Importing Complete


Load data from drive:

In [ ]:
data = sio.loadmat('/content/drive/MyDrive/5features.mat')
data1 = np.asarray(data['data'])
Normal = data1[:15,:]
MCI = data1[15:22,:]
AD = data1[22:,:]

Load data from local address:

In [2]:
data = sio.loadmat('5features.mat')
data1 = np.asarray(data['data'])
Normal = data1[:15,:]
MCI = data1[15:22,:]
AD = data1[22:,:]

# Grid search, Normal (0) vs MCI (1)



In [3]:
train_data = np.append(Normal,MCI,axis=0)
num_feature = 5
X = train_data[:,0:num_feature]
y = train_data[:,num_feature]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
parameters = {'n_estimators':[10,100,500,1000],'max_depth':[2, 5, 10], 'min_samples_split':[2,4,8]}
RF = RandomForestClassifier(random_state=0)
clf = GridSearchCV(RF, parameters)
clf.fit(X, y)

GridSearchCV(estimator=RandomForestClassifier(random_state=0),
             param_grid={'max_depth': [2, 5, 10],
                         'min_samples_split': [2, 4, 8],
                         'n_estimators': [10, 100, 500, 1000]})

best parameter

In [4]:
print(clf.best_params_)

{'max_depth': 2, 'min_samples_split': 2, 'n_estimators': 100}


Cross validation and classification metrics

In [5]:
train_data = np.append(Normal,MCI,axis=0)
num_feature = 5
X = train_data[:,0:num_feature]
y = train_data[:,num_feature]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
cv = StratifiedKFold(n_splits=5)
scoring = ['precision_macro', 'recall_macro', 'balanced_accuracy', 'accuracy','precision','recall']
model = RandomForestClassifier(max_depth=2, min_samples_split= 2, n_estimators= 100, random_state=0)
scores = cross_validate(model, X, y, cv=cv, scoring=scoring)

print('accuracy:')
print(scores['test_accuracy'].mean())
print(scores['test_accuracy'].std())

print('balanced_accuracy:')
print(scores['test_accuracy'].mean())
print(scores['test_accuracy'].std())

print('precision:')
print(scores['test_precision'].mean())
print(scores['test_precision'].std())

print('precision macro:')
print(scores['test_precision_macro'].mean())
print(scores['test_precision_macro'].std())

print('recall:')
print(scores['test_recall'].mean())
print(scores['test_recall'].std())

print('recall macro:')
print(scores['test_recall_macro'].mean())
print(scores['test_recall_macro'].std())

accuracy:
0.9
0.2
balanced_accuracy:
0.9
0.2
precision:
0.8666666666666666
0.26666666666666666
precision macro:
0.9333333333333333
0.13333333333333336
recall:
1.0
0.0
recall macro:
0.9333333333333333
0.13333333333333336


# Grid search, AD (1) vs MCI (0)

In [6]:
train_data = np.append(AD,MCI,axis=0)
num_feature = 5
X = train_data[:,0:num_feature]
y = abs(train_data[:,num_feature]-2)
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
parameters = {'n_estimators':[10,100,500,1000],'max_depth':[2, 5, 10], 'min_samples_split':[2,4,8]}
RF = RandomForestClassifier(random_state=0)
clf1 = GridSearchCV(RF, parameters)
clf1.fit(X, y)

GridSearchCV(estimator=RandomForestClassifier(random_state=0),
             param_grid={'max_depth': [2, 5, 10],
                         'min_samples_split': [2, 4, 8],
                         'n_estimators': [10, 100, 500, 1000]})

best parameter

In [7]:
print(clf.best_params_)

{'max_depth': 2, 'min_samples_split': 2, 'n_estimators': 100}


Cross validation and classification metrics


In [8]:
train_data = np.append(AD,MCI,axis=0)
num_feature = 5
X = train_data[:,0:num_feature]
y = abs(train_data[:,num_feature]-2)
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
cv = StratifiedKFold(n_splits=5)
scoring = ['precision_macro', 'recall_macro', 'balanced_accuracy', 'accuracy','precision','recall']
model = RandomForestClassifier(max_depth=2, min_samples_split= 2, n_estimators= 100, random_state=0)
scores = cross_validate(model, X, y, cv=cv, scoring=scoring)

print('accuracy:')
print(scores['test_accuracy'].mean())
print(scores['test_accuracy'].std())

print('balanced_accuracy:')
print(scores['test_accuracy'].mean())
print(scores['test_accuracy'].std())

print('precision:')
print(scores['test_precision'].mean())
print(scores['test_precision'].std())

print('precision macro:')
print(scores['test_precision_macro'].mean())
print(scores['test_precision_macro'].std())

print('recall:')
print(scores['test_recall'].mean())
print(scores['test_recall'].std())

print('recall macro:')
print(scores['test_recall_macro'].mean())
print(scores['test_recall_macro'].std())

accuracy:
0.9
0.1224744871391589
balanced_accuracy:
0.9
0.1224744871391589
precision:
0.8333333333333334
0.21081851067789195
precision macro:
0.9166666666666666
0.10540925533894599
recall:
1.0
0.0
recall macro:
0.9166666666666666
0.10540925533894599


#  Random Forest (Normal(0) vs MCI (1) + MCI (1) vs AD (2)) with 5 Features:

In [29]:
from sklearn.model_selection import train_test_split 
from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#load data
data = sio.loadmat('5features.mat')
data1 = np.asarray(data['data'])

X = data1[:,0:5]
y = data1[:,5]


outer_cv = StratifiedKFold(n_splits = 5, shuffle=True, random_state=1)

# enumerate over splits
outer_acc = list()
outer_rec = list()
outer_pre = list()
for train_i, test_i in outer_cv.split(X, y):
    # split data
    X_train, X_test = X[train_i, :], X[test_i, :]
    y_train, y_test = y[train_i], y[test_i]
    
    scaler = StandardScaler()
    scaler.fit(X_train)

    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)
    
    X_train1 = X_train[np.where((y_train==0) | (y_train==1)), :]
    X_train1 = np.reshape(X_train1,(X_train1.shape[1],X_train1.shape[2]))
    y_train1 = y_train[np.where((y_train==0) | (y_train==1))]

    X_train2 = X_train[np.where((y_train==1) | (y_train==2)), :]
    X_train2 = np.reshape(X_train2,(X_train2.shape[1],X_train2.shape[2]))
    y_train2 = y_train[np.where((y_train==1) | (y_train==2))]
    
    
    # SVM model: rbf kernel
    model1 = RandomForestClassifier(max_depth=2, min_samples_split= 2, n_estimators= 100, random_state=0)
    model2 = RandomForestClassifier(max_depth=2, min_samples_split= 2, n_estimators= 100, random_state=0)
    model1.fit(X_train1, y_train1)
    model2.fit(X_train2, y_train2)
    

    # evaluate the model
    ypred1 = model1.predict_proba(X_test)
    ypred2 = model2.predict_proba(X_test)
    
    p_normal = ypred1[:,0]
    p_mci = (ypred1[:,1]+ypred2[:,0])/2
    p_ad = ypred2[:,1]
    
    p = np.array([p_normal, p_mci, p_ad]).T
    print(p)
    
    y_pred = np.argmax(p, axis=1)
    acc = balanced_accuracy_score(y_test, y_pred)
    pre = precision_score(y_test, y_pred, average='weighted')
    rec = recall_score(y_test, y_pred, average='weighted')
    print(y_test)
    print(y_pred)
    outer_acc.append(acc)
    outer_pre.append(pre)
    outer_rec.append(rec)
    print('>acc=%.3f' % (acc))

# # overall estimated accuracy of the model
print('Estimated Accuracy for random forest: %.3f (%.3f)' % (np.mean(outer_acc), np.std(outer_acc)))
print('Estimated Precision for random forest: %.3f (%.3f)' % (np.mean(outer_pre), np.std(outer_pre)))
print('Estimated Recall for random forest: %.3f (%.3f)' % (np.mean(outer_rec), np.std(outer_rec)))





[[0.50385714 0.6009881  0.29416667]
 [0.93575758 0.06003788 0.94416667]
 [0.98575758 0.02212121 0.97      ]
 [0.07052381 0.91557143 0.09833333]
 [0.15719048 0.8647381  0.11333333]
 [0.91575758 0.04670455 0.99083333]
 [0.53711472 0.51935931 0.42416667]]
[0. 0. 0. 1. 1. 2. 2.]
[1 2 0 1 1 2 0]
>acc=0.611
[[0.79       0.115      0.98      ]
 [0.845      0.0875     0.98      ]
 [0.33777778 0.77744444 0.10733333]
 [0.71111111 0.41077778 0.46733333]
 [0.62777778 0.47944444 0.41333333]
 [0.83       0.09       0.99      ]
 [0.81527778 0.52069444 0.14333333]]
[0. 0. 0. 1. 1. 2. 2.]
[2 2 1 0 0 2 0]
>acc=0.167
[[0.94833333 0.13977778 0.77211111]
 [0.99833333 0.01325    0.97516667]
 [0.96516667 0.02041667 0.994     ]
 [0.21034524 0.85960516 0.07044444]
 [0.725      0.19725    0.8805    ]
 [0.96516667 0.02041667 0.994     ]
 [0.95641667 0.02479167 0.994     ]]
[0. 0. 0. 1. 2. 2. 2.]
[0 0 2 1 2 2 2]
>acc=0.889
[[0.78835354 0.42519823 0.36125   ]
 [1.         0.06058333 0.87883333]
 [0.46028211 0.4588

#  Random Forest (Normal(0) vs MCI (1) + MCI (1) vs AD (2)) with 4 Features:

In [23]:
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn.metrics import balanced_accuracy_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#load data
data = sio.loadmat('ML_data1.mat')
data1 = np.asarray(data['data'])

X = data1[:,0:4]
y = data1[:,4]


outer_cv = StratifiedKFold(n_splits = 5, shuffle=True, random_state=1)

# enumerate over splits
outer_acc = list()
outer_rec = list()
outer_pre = list()
for train_i, test_i in outer_cv.split(X, y):
    # split data
    X_train, X_test = X[train_i, :], X[test_i, :]
    y_train, y_test = y[train_i], y[test_i]
    
    scaler = StandardScaler()
    scaler.fit(X_train)

    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)
    
    X_train1 = X_train[np.where((y_train==0) | (y_train==1)), :]
    X_train1 = np.reshape(X_train1,(X_train1.shape[1],X_train1.shape[2]))
    y_train1 = y_train[np.where((y_train==0) | (y_train==1))]

    X_train2 = X_train[np.where((y_train==1) | (y_train==2)), :]
    X_train2 = np.reshape(X_train2,(X_train2.shape[1],X_train2.shape[2]))
    y_train2 = y_train[np.where((y_train==1) | (y_train==2))]
    
    
    # SVM model: rbf kernel
    model1 = RandomForestClassifier(max_depth=2, min_samples_split= 2, n_estimators= 100, random_state=0)
    model2 = RandomForestClassifier(max_depth=2, min_samples_split= 2, n_estimators= 100, random_state=0)
    model1.fit(X_train1, y_train1)
    model2.fit(X_train2, y_train2)
    

    # evaluate the model
    ypred1 = model1.predict_proba(X_test)
    ypred2 = model2.predict_proba(X_test)
    
    p_normal = ypred1[:,0]
    p_mci = (ypred1[:,1]+ypred2[:,0])/2
    p_ad = ypred2[:,1]
    
    p = np.array([p_normal, p_mci, p_ad]).T
    print(p)
    
    y_pred = np.argmax(p, axis=1)
    acc = balanced_accuracy_score(y_test, y_pred)
    pre = precision_score(y_test, y_pred, average='weighted')
    rec = recall_score(y_test, y_pred, average='weighted')
    print(y_test)
    print(y_pred)
    outer_acc.append(acc)
    outer_pre.append(pre)
    outer_rec.append(rec)
    print('>acc=%.3f' % (acc))

# # overall estimated accuracy of the model
print('Estimated Accuracy for random forest: %.3f (%.3f)' % (np.mean(outer_acc), np.std(outer_acc)))
print('Estimated Precision for random forest: %.3f (%.3f)' % (np.mean(outer_pre), np.std(outer_pre)))
print('Estimated Recall for random forest: %.3f (%.3f)' % (np.mean(outer_rec), np.std(outer_rec)))





[[0.51       0.55823214 0.37353571]
 [0.953      0.05227381 0.94245238]
 [0.97166667 0.03119048 0.96595238]
 [0.05633333 0.90526786 0.13313095]
 [0.13833333 0.85576786 0.15013095]
 [0.94133333 0.04844048 0.96178571]
 [0.50466667 0.43253571 0.6302619 ]]
[0. 0. 0. 1. 1. 2. 2.]
[1 0 0 1 1 2 2]
>acc=0.889
[[0.59       0.22       0.97      ]
 [0.64       0.22       0.92      ]
 [0.61083333 0.55736905 0.27442857]
 [0.583      0.62057738 0.17584524]
 [0.32583333 0.74766071 0.17884524]
 [0.65       0.19066667 0.96866667]
 [0.69333333 0.51549405 0.27567857]]
[0. 0. 0. 1. 1. 2. 2.]
[2 2 0 1 1 2 0]
>acc=0.611
[[0.95909091 0.06665314 0.90760281]
 [0.99909091 0.00882576 0.98325758]
 [0.97409091 0.01440909 0.99709091]
 [0.30882107 0.78174639 0.12768615]
 [0.57609091 0.35590909 0.71209091]
 [0.97409091 0.01440909 0.99709091]
 [0.92284091 0.04503409 0.98709091]]
[0. 0. 0. 1. 2. 2. 2.]
[0 0 2 1 2 2 2]
>acc=0.889
[[0.81153968 0.40513889 0.37818254]
 [1.         0.07696429 0.84607143]
 [0.56819048 0.3774

# Grid search, Normal (0) vs MCI (1) vs AD (2) 
Three-class classification with 5 features

In [31]:
train_data = np.concatenate((Normal,MCI,AD),axis=0)
num_feature = 5
X = train_data[:,0:num_feature]
y = train_data[:,num_feature]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
parameters = {'n_estimators':[10,100,500,1000],'max_depth':[2, 5, 10], 'min_samples_split':[2,4,8]}
RF = RandomForestClassifier(random_state=0)
clf2 = GridSearchCV(RF, parameters)
clf2.fit(X, y)

GridSearchCV(estimator=RandomForestClassifier(random_state=0),
             param_grid={'max_depth': [2, 5, 10],
                         'min_samples_split': [2, 4, 8],
                         'n_estimators': [10, 100, 500, 1000]})

In [32]:
print(clf2.best_params_)

{'max_depth': 2, 'min_samples_split': 2, 'n_estimators': 10}


In [41]:
train_data = np.concatenate((Normal,MCI,AD),axis=0)
num_feature = 5
X = train_data[:,0:num_feature]
y = train_data[:,num_feature]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
cv = StratifiedKFold(n_splits=5)
scoring = [ 'balanced_accuracy', 'accuracy']
model = RandomForestClassifier(max_depth=2, min_samples_split=2, n_estimators=10, random_state=0)
scores = cross_validate(model, X, y, cv=cv, scoring=scoring)

print('accuracy:')
print(scores['test_accuracy'].mean())
print(scores['test_accuracy'].std())

print('balanced_accuracy:')
print(scores['test_accuracy'].mean())
print(scores['test_accuracy'].std())


accuracy:
0.6571428571428571
0.19378085666072195
balanced_accuracy:
0.6571428571428571
0.19378085666072195
