In [ ]:
from google.colab import drive
drive.mount('/content/drive')
!ls /content/drive/MyDrive/5features.mat

In [381]:
from sklearn.model_selection import train_test_split 
from sklearn.metrics import accuracy_score
import scipy.io as sio
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold
from sklearn.metrics import classification_report
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import GridSearchCV, cross_val_score, KFold
from sklearn.metrics import classification_report, accuracy_score, make_scorer
from sklearn.model_selection import cross_validate
from sklearn.model_selection import StratifiedKFold
print('Importing Complete')

Importing Complete


Load data from drive:

In [ ]:
data = sio.loadmat('/content/drive/MyDrive/5features.mat')
data1 = np.asarray(data['data'])
Normal = data1[:15,:]
MCI = data1[15:22,:]
AD = data1[22:,:]

Load data from local address:

In [382]:
data = sio.loadmat('5features.mat')
data1 = np.asarray(data['data'])
Normal = data1[:15,:]
MCI = data1[15:22,:]
AD = data1[22:,:]

# Grid search, Normal (0) vs MCI (1)



In [383]:
train_data = np.append(Normal,MCI,axis=0)
num_feature = 5
X = train_data[:,0:num_feature]
y = train_data[:,num_feature]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
parameters = {'C':[1,2,10],'gamma':[0.1, 1, 3]}
svc = SVC(kernel='rbf')
clf = GridSearchCV(svc, parameters)
clf.fit(X, y)

GridSearchCV(estimator=SVC(),
             param_grid={'C': [1, 2, 10], 'gamma': [0.1, 1, 3]})

best parameter

In [384]:
print(clf.best_params_)

{'C': 2, 'gamma': 1}


Cross validation and classification metrics --- linear

In [385]:
train_data = np.append(Normal,MCI,axis=0)
num_feature = 5
X = train_data[:,0:num_feature]
y = train_data[:,num_feature]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
cv = StratifiedKFold(n_splits=5)
scoring = ['precision_macro', 'recall_macro', 'balanced_accuracy', 'accuracy','precision','recall']
model = SVC(kernel = 'linear', C = 2, gamma=0.1)
scores = cross_validate(model, X, y, cv=cv, scoring=scoring)

print('accuracy:')
print(scores['test_accuracy'].mean())
print(scores['test_accuracy'].std())

print('balanced_accuracy:')
print(scores['test_accuracy'].mean())
print(scores['test_accuracy'].std())

print('precision:')
print(scores['test_precision'].mean())
print(scores['test_precision'].std())

print('precision macro:')
print(scores['test_precision_macro'].mean())
print(scores['test_precision_macro'].std())

print('recall:')
print(scores['test_recall'].mean())
print(scores['test_recall'].std())

print('recall macro:')
print(scores['test_recall_macro'].mean())
print(scores['test_recall_macro'].std())

accuracy:
0.9099999999999999
0.11135528725660043
balanced_accuracy:
0.9099999999999999
0.11135528725660043
precision:
0.9
0.2
precision macro:
0.925
0.1
recall:
0.9
0.20000000000000004
recall macro:
0.9166666666666666
0.10540925533894599


Cross validation and classification metrics --- RBF


In [386]:
train_data = np.append(Normal,MCI,axis=0)
num_feature = 5
X = train_data[:,0:num_feature]
y = train_data[:,num_feature]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
cv = StratifiedKFold(n_splits=5)
scoring = ['precision_macro', 'recall_macro', 'balanced_accuracy', 'accuracy','precision','recall']
model = SVC(kernel = 'rbf', C = 2, gamma=1)
scores = cross_validate(model, X, y, cv=cv, scoring=scoring)

print('accuracy:')
print(scores['test_accuracy'].mean())
print(scores['test_accuracy'].std())

print('balanced_accuracy:')
print(scores['test_accuracy'].mean())
print(scores['test_accuracy'].std())

print('precision:')
print(scores['test_precision'].mean())
print(scores['test_precision'].std())

print('precision macro:')
print(scores['test_precision_macro'].mean())
print(scores['test_precision_macro'].std())

print('recall:')
print(scores['test_recall'].mean())
print(scores['test_recall'].std())

print('recall macro:')
print(scores['test_recall_macro'].mean())
print(scores['test_recall_macro'].std())

accuracy:
0.8699999999999999
0.10770329614269006
balanced_accuracy:
0.8699999999999999
0.10770329614269006
precision:
0.8
0.4
precision macro:
0.825
0.2318404623873926
recall:
0.6
0.37416573867739417
recall macro:
0.8
0.18708286933869706


C:\Users\nahaleh fatemi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\nahaleh fatemi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Grid search, AD (1) vs MCI (0)

In [387]:
train_data = np.append(AD,MCI,axis=0)
num_feature = 5
X = train_data[:,0:num_feature]
y = abs(train_data[:,num_feature]-2)
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
parameters = {'C':[1,2,10],'gamma':[0.1, 1, 3]}
svc = SVC(kernel='linear')
clf1 = GridSearchCV(svc, parameters)
clf1.fit(X, y)

GridSearchCV(estimator=SVC(kernel='linear'),
             param_grid={'C': [1, 2, 10], 'gamma': [0.1, 1, 3]})

best parameter

In [388]:
print(clf.best_params_)

{'C': 2, 'gamma': 1}


Cross validation and classification metrics --- linear kernel


In [389]:
train_data = np.append(AD,MCI,axis=0)
num_feature = 5
X = train_data[:,0:num_feature]
y = abs(train_data[:,num_feature]-2)
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
cv = StratifiedKFold(n_splits=5)
scoring = ['precision_macro', 'recall_macro', 'balanced_accuracy', 'accuracy','precision','recall']
model = SVC(kernel = 'linear', C = 1, gamma=0.1)
scores = cross_validate(model, X, y, cv=cv, scoring=scoring)

print('accuracy:')
print(scores['test_accuracy'].mean())
print(scores['test_accuracy'].std())

print('balanced_accuracy:')
print(scores['test_accuracy'].mean())
print(scores['test_accuracy'].std())

print('precision:')
print(scores['test_precision'].mean())
print(scores['test_precision'].std())

print('precision macro:')
print(scores['test_precision_macro'].mean())
print(scores['test_precision_macro'].std())

print('recall:')
print(scores['test_recall'].mean())
print(scores['test_recall'].std())

print('recall macro:')
print(scores['test_recall_macro'].mean())
print(scores['test_recall_macro'].std())

accuracy:
0.8
0.18708286933869706
balanced_accuracy:
0.8
0.18708286933869706
precision:
0.6333333333333333
0.3711842908553348
precision macro:
0.7833333333333334
0.24494897427831783
recall:
0.8
0.4
recall macro:
0.7833333333333333
0.24494897427831783


Cross validation and classification metrics --- RBF kernel


In [390]:
train_data = np.append(AD,MCI,axis=0)
num_feature = 5
X = train_data[:,0:num_feature]
y = abs(train_data[:,num_feature]-2)
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
cv = StratifiedKFold(n_splits=5)
scoring = ['precision_macro', 'recall_macro', 'balanced_accuracy', 'accuracy','precision','recall']
model = SVC(kernel = 'rbf', C = 1, gamma=0.1)
scores = cross_validate(model, X, y, cv=cv, scoring=scoring)

print('accuracy:')
print(scores['test_accuracy'].mean())
print(scores['test_accuracy'].std())

print('balanced_accuracy:')
print(scores['test_accuracy'].mean())
print(scores['test_accuracy'].std())

print('precision:')
print(scores['test_precision'].mean())
print(scores['test_precision'].std())

print('precision macro:')
print(scores['test_precision_macro'].mean())
print(scores['test_precision_macro'].std())

print('recall:')
print(scores['test_recall'].mean())
print(scores['test_recall'].std())

print('recall macro:')
print(scores['test_recall_macro'].mean())
print(scores['test_recall_macro'].std())

accuracy:
0.85
0.1224744871391589
balanced_accuracy:
0.85
0.1224744871391589
precision:
0.8333333333333334
0.21081851067789195
precision macro:
0.8833333333333332
0.10000000000000002
recall:
0.9
0.2
recall macro:
0.8666666666666666
0.11303883305208781


# RBF SVM (Normal(0) vs MCI (1) + MCI (1) vs AD (2)) with 5 Features:

In [502]:
# try nested cv for rbf kernel SVM
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn.metrics import accuracy_score
from sklearn.metrics import balanced_accuracy_score
import scipy.io as sio
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
#load data
data = sio.loadmat('5features.mat')
data1 = np.asarray(data['data'])

X = data1[:,0:5]
y = data1[:,5]


outer_cv = StratifiedKFold(n_splits = 5, shuffle=True, random_state=1)

# enumerate over splits
outer_acc = list()
outer_rec = list()
outer_pre = list()
for train_i, test_i in outer_cv.split(X, y):
    # split data
    X_train, X_test = X[train_i, :], X[test_i, :]
    y_train, y_test = y[train_i], y[test_i]
    
    scaler = StandardScaler()
    scaler.fit(X_train)

    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)
    
    X_train1 = X_train[np.where((y_train==0) | (y_train==1)), :]
    X_train1 = np.reshape(X_train1,(X_train1.shape[1],X_train1.shape[2]))
    y_train1 = y_train[np.where((y_train==0) | (y_train==1))]

    X_train2 = X_train[np.where((y_train==1) | (y_train==2)), :]
    X_train2 = np.reshape(X_train2,(X_train2.shape[1],X_train2.shape[2]))
    y_train2 = y_train[np.where((y_train==1) | (y_train==2))]
    
    
    # SVM model: rbf kernel
    model1 = SVC(kernel = 'rbf', C=2, gamma=1, probability=True)
    model2 = SVC(kernel = 'rbf', C=2, gamma=1, probability=True)
    model1.fit(X_train1, y_train1)
    model2.fit(X_train2, y_train2)
    

    # evaluate the model
    ypred1 = model1.predict_proba(X_test)
    ypred2 = model2.predict_proba(X_test)
    
    p_normal = ypred1[:,0]
    p_mci = (ypred1[:,1]+ypred2[:,0])/2
    p_ad = ypred2[:,1]
    
    p = np.array([p_normal, p_mci, p_ad]).T
    print(p)
    
    y_pred = np.argmax(p, axis=1)
    acc = balanced_accuracy_score(y_test, y_pred)
    pre = precision_score(y_test, y_pred, average='weighted')
    rec = recall_score(y_test, y_pred, average='weighted')
    print(y_test)
    print(y_pred)
    outer_acc.append(acc)
    outer_pre.append(pre)
    outer_rec.append(rec)
    print('>acc=%.3f' % (acc))

# # overall estimated accuracy of the model
print('Estimated Accuracy for rbf SVM: %.3f (%.3f)' % (np.mean(outer_acc), np.std(outer_acc)))
print('Estimated Precision for rbf SVM: %.3f (%.3f)' % (np.mean(outer_pre), np.std(outer_pre)))
print('Estimated Recall for rbf SVM: %.3f (%.3f)' % (np.mean(outer_rec), np.std(outer_rec)))





[[0.80350599 0.25440683 0.68768036]
 [0.95346061 0.05084455 0.94485029]
 [0.94600576 0.06375111 0.92649203]
 [0.02776427 0.963727   0.04478173]
 [0.40903684 0.5662469  0.45846936]
 [0.88539949 0.08867191 0.93725669]
 [0.60061582 0.38275906 0.63386606]]
[0. 0. 0. 1. 1. 2. 2.]
[0 0 0 1 1 2 2]
>acc=1.000
[[0.70317005 0.25739266 0.78204462]
 [0.88496122 0.12000968 0.87501942]
 [0.70260521 0.28865316 0.72008848]
 [0.41878848 0.55029921 0.48061309]
 [0.71543627 0.28293679 0.71869016]
 [0.73613026 0.24558543 0.77269888]
 [0.90015028 0.19110385 0.71764201]]
[0. 0. 0. 1. 1. 2. 2.]
[2 0 2 1 2 2 0]
>acc=0.444
[[0.77262394 0.2366674  0.75404126]
 [0.89767304 0.15227313 0.7977807 ]
 [0.62125961 0.36694834 0.64484371]
 [0.34725182 0.65376395 0.34522028]
 [0.65837361 0.33817666 0.66527308]
 [0.64410708 0.34093384 0.67402524]
 [0.6215228  0.36641357 0.64565006]]
[0. 0. 0. 1. 2. 2. 2.]
[0 0 2 1 2 2 2]
>acc=0.889
[[0.93189002 0.23299124 0.6021275 ]
 [0.74621068 0.27276871 0.70825191]
 [0.55107828 0.2909

C:\Users\nahaleh fatemi\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# RBF SVM (Normal(0) vs MCI (1) + MCI (1) vs AD (2)) with 4 Features:

In [226]:
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn.metrics import accuracy_score
from sklearn.metrics import balanced_accuracy_score
import scipy.io as sio
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

#load data
data = sio.loadmat('ML_data1.mat')
data1 = np.asarray(data['data'])

X = data1[:,0:4]
y = data1[:,4]



outer_cv = StratifiedKFold(n_splits = 5, shuffle=True, random_state=1)

# enumerate over splits
outer_results = list()
for train_i, test_i in outer_cv.split(X, y):
    # split data
    X_train, X_test = X[train_i, :], X[test_i, :]
    y_train, y_test = y[train_i], y[test_i]
    
    scaler = StandardScaler()
    scaler.fit(X_train)

    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)
    
    X_train1 = X_train[np.where((y_train==0) | (y_train==1)), :]
    X_train1 = np.reshape(X_train1,(X_train1.shape[1],X_train1.shape[2]))
    y_train1 = y_train[np.where((y_train==0) | (y_train==1))]

    X_train2 = X_train[np.where((y_train==1) | (y_train==2)), :]
    X_train2 = np.reshape(X_train2,(X_train2.shape[1],X_train2.shape[2]))
    y_train2 = y_train[np.where((y_train==1) | (y_train==2))]
    
    
    # SVM model: rbf kernel
    model1 = SVC(kernel = 'rbf', C=1, gamma=0.1, probability=True)
    model2 = SVC(kernel = 'rbf',  C=1, gamma=0.1,probability=True)
    model1.fit(X_train1, y_train1)
    model2.fit(X_train2, y_train2)
    

    # evaluate the model
    ypred1 = model1.predict_proba(X_test)
    ypred2 = model2.predict_proba(X_test)
    
    p_normal = ypred1[:,0]
    p_mci = (ypred1[:,1]+ypred2[:,0])/2
    p_ad = ypred2[:,1]
    
    p = np.array([p_normal, p_mci, p_ad]).T
    print(p)
    
    y_pred = np.argmax(p, axis=1)
    acc = balanced_accuracy_score(y_test, y_pred)
    print(y_test)
    print(y_pred)
    outer_results.append(acc)
    print('>acc=%.3f' % (acc))

# # overall estimated accuracy of the model
print('Estimated Accuracy for rbf SVM: %.3f (%.3f)' % (np.mean(outer_results), np.std(outer_results)))





[[0.77409392 0.30927244 0.6073612 ]
 [0.87047688 0.13071043 0.86810227]
 [0.91351822 0.09484259 0.89679659]
 [0.36508263 0.64984055 0.33523628]
 [0.46547925 0.60252319 0.32947438]
 [0.87924028 0.10894228 0.90287516]
 [0.52424609 0.43895588 0.59784215]]
[0. 0. 0. 1. 1. 2. 2.]
[0 0 0 1 1 2 2]
>acc=1.000
[[0.64274105 0.20537015 0.94651865]
 [0.87820409 0.09899523 0.92380546]
 [0.61823942 0.42820531 0.52534997]
 [0.15624552 0.81100392 0.22174663]
 [0.44787864 0.62345666 0.30520804]
 [0.59954816 0.27469028 0.85107127]
 [0.87290413 0.34506646 0.43696295]]
[0. 0. 0. 1. 1. 2. 2.]
[2 2 0 1 1 2 0]
>acc=0.611
[[0.94703503 0.107797   0.83737098]
 [0.96449504 0.07906405 0.87737685]
 [0.94763688 0.102245   0.84787312]
 [0.24076608 0.67604454 0.40714484]
 [0.82206894 0.1772309  0.82346927]
 [0.96943011 0.07947013 0.87162963]
 [0.94100866 0.10303477 0.8529218 ]]
[0. 0. 0. 1. 2. 2. 2.]
[0 0 0 1 2 0 0]
>acc=0.778
[[0.75337721 0.35877523 0.52907233]
 [0.93906059 0.10668772 0.84756398]
 [0.36706277 0.5372

Performance of RBF SVM with 4 features (accuracy, precision, recall):

In [350]:
outer_acc = list()
outer_pre = list()
outer_rec = list()
y_test = [0, 0, 0, 1, 2, 2, 2]
y_pred = [0, 0, 0, 1, 2, 2, 2]
acc = balanced_accuracy_score(y_test, y_pred)
pre = precision_score(y_test, y_pred, average='weighted')
rec = recall_score(y_test, y_pred, average='weighted')
outer_acc.append(acc)
outer_pre.append(pre)
outer_rec.append(rec)

y_test = [0, 0, 0, 1, 2, 2, 2]
y_pred = [0, 0, 2, 1, 0, 0, 0]
acc = balanced_accuracy_score(y_test, y_pred)
pre = precision_score(y_test, y_pred, average='weighted')
rec = recall_score(y_test, y_pred, average='weighted')
outer_acc.append(acc)
outer_pre.append(pre)
outer_rec.append(rec)


y_test = [0, 0, 0, 1, 2, 2, 2]
y_pred = [0, 0, 0, 1, 2, 0, 0]
acc = balanced_accuracy_score(y_test, y_pred)
pre = precision_score(y_test, y_pred, average='weighted')
rec = recall_score(y_test, y_pred, average='weighted')
outer_acc.append(acc)
outer_pre.append(pre)
outer_rec.append(rec)


y_test = [0, 0, 0, 1, 1, 2, 2]
y_pred = [2, 2, 0, 1, 1, 2, 0]
acc = balanced_accuracy_score(y_test, y_pred)
pre = precision_score(y_test, y_pred, average='weighted')
rec = recall_score(y_test, y_pred, average='weighted')
outer_acc.append(acc)
outer_pre.append(pre)
outer_rec.append(rec)


y_test = [0, 0, 0, 1, 1, 2, 2]
y_pred = [0, 0, 0, 1, 1, 2, 2]
acc = balanced_accuracy_score(y_test, y_pred)
pre = precision_score(y_test, y_pred, average='weighted')
rec = recall_score(y_test, y_pred, average='weighted')
outer_acc.append(acc)
outer_pre.append(pre)
outer_rec.append(rec)

print('Estimated Accuracy for rbf SVM: %.3f (%.3f)' % (np.mean(outer_acc), np.std(outer_acc)))
print('Estimated Precision for rbf SVM: %.3f (%.3f)' % (np.mean(outer_pre), np.std(outer_pre)))
print('Estimated Recall for rbf SVM: %.3f (%.3f)' % (np.mean(outer_rec), np.std(outer_rec)))


Estimated Accuracy for rbf SVM: 0.789 (0.187)
Estimated Precision for rbf SVM: 0.748 (0.263)
Estimated Recall for rbf SVM: 0.743 (0.229)


# Grid search, Normal (0) vs MCI (1) vs AD (2)
Three-class classification with 5 features

In [595]:
train_data = np.concatenate((Normal,MCI,AD),axis=0)
num_feature = 5
X = train_data[:,0:num_feature]
y = train_data[:,num_feature]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
parameters = {'C':[1,2,10],'gamma':[0.1, 1, 3]}
svc = SVC(kernel='rbf',decision_function_shape='ovo')
clf2 = GridSearchCV(svc, parameters)
clf2.fit(X, y)

GridSearchCV(estimator=SVC(decision_function_shape='ovo'),
             param_grid={'C': [1, 2, 10], 'gamma': [0.1, 1, 3]})

best parameter

In [596]:
print(clf2.best_params_)

{'C': 1, 'gamma': 0.1}


In [597]:
train_data = np.concatenate((Normal,MCI,AD),axis=0)
num_feature = 5
X = train_data[:,0:num_feature]
y = train_data[:,num_feature]
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)
cv = StratifiedKFold(n_splits=5)
scoring = [ 'balanced_accuracy', 'accuracy']
model = SVC(kernel = 'rbf', C = 1, gamma=0.1, decision_function_shape='ovo')
scores = cross_validate(model, X, y, cv=cv, scoring=scoring)

print('accuracy:')
print(scores['test_accuracy'].mean())
print(scores['test_accuracy'].std())

print('balanced_accuracy:')
print(scores['test_accuracy'].mean())
print(scores['test_accuracy'].std())

# print('precision:')
# print(scores['test_precision'].mean())
# print(scores['test_precision'].std())

# print('precision macro:')
# print(scores['test_precision_macro'].mean())
# print(scores['test_precision_macro'].std())

# print('recall:')
# print(scores['test_recall'].mean())
# print(scores['test_recall'].std())

# print('recall macro:')
# print(scores['test_recall_macro'].mean())
# print(scores['test_recall_macro'].std())

accuracy:
0.6571428571428571
0.17142857142857143
balanced_accuracy:
0.6571428571428571
0.17142857142857143
